/* AUTO GENERATED BY make. DO NOT EDIT! */

#define RELEASE "0.2"
#define BLAME "cpasjuste@laptop i686"
#define DATE "2009-08-31"

#define VERSION RELEASE "-cvs-" DATE
#define LONGVERSION VERSION " (" BLAME ")"
